#! /bin/sh

sxhkd &
bspc config border_width 2
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config normal_border_color "#000000"
bspc config focused_border_color "#FF0000"

bspc monitor -d I II III IV V VI VII VIII IX 

polybar mybar

